CREATE TABLE USER (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	description TEXT,
	image TEXT,
	deleted BOOL DEFAULT FALSE,
);

CREATE TABLE ADMIN (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER FOREIGN KEY REFERENCES USER(id)
	);
	
CREATE TABLE CATEGORY (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description TEXT NOT NULL,
	);
	
	
CREATE TABLE AUCTION (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description TEXT NOT NULL,
	image TEXT NOT NULL,
	active BOOL NOT NULL DEFAULT TRUE,
	start TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	owner_id INTEGER NOT NULL FOREIGN KEY REFERENCES USER(id)
	);

CREATE TABLE NOTIFICATION (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	message TEXT NOT NULL,
	auction_id INTEGER FOREIGN KEY REFERENCES AUCTION(id),
	user_id INTEGER FOREIGN KEY REFERENCES USER(id)
	);
	
CREATE TABLE BID(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	amount FLOAT NOT NULL,
    	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	user_id INTEGER FOREIGN KEY REFERENCES USER(id),
	auction_id INTEGER FOREIGN KEY REFERENCES AUCTION(id),
	top_bid BOOL NOT NULL DEFAULT TRUE
	);
	
CREATE TABLE FOLLOW AUCTION(   -- acho que assim dá
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL FOREIGN KEY REFERENCES USER(id),
	auction_id INTEGER NOT NULL FOREIGN KEY REFERENCES auction(id),
	
	);

