SET search_path to lbaw23113;

insert into users (username, email, name, description, password, blocked, rate, type) values ('andreia', 'andreia@lbaw.com', 'Andreia Silva', 'User default da Andreia.', '$2y$10$omqxg2RzFdFk.kpcYvgkme2YcEbaqJkLUhvwvYBI4ebNe9c9MckBa', false, 1, 'admin');
insert into users (username, email, name, description, password, blocked, rate, type) values ('belchior', 'belchior@lbaw.com', 'João Belchior', 'User default do Belchior.', '$2y$10$iYrWVx4Ef4AK9Q6xsVReTubMx.IVmPucMIVWYgXdt4tWJWYZeEE3G', false, 1, 'user');
insert into users (username, email, name, description, password, blocked, rate, type) values ('marcelino', 'marcelino@lbaw.com', 'Pedro Marcelino', 'User default do Marcelino.', '$2y$10$NW.3yOcuxmGek6kgbmO3fuK0EiF06Ll/gZ6/NaoCj34KqmecxNlTi', false, 1, 'user');
insert into users (username, email, name, description, password, blocked, rate, type) values ('veiga', 'veiga@lbaw.com', 'José Veiga', 'User default do Veiga.', '$2y$10$CSEsyfvYOOfXw6XqOTyzMOI9wcVJWPv/mr8ehQ9LatnU9CkFxI./S', false, 1, 'user');
insert into users (username, email, name, description, password, blocked, rate, type) values ('default', 'default@default.com', 'Default', 'User default.', '$2y$10$v04j1no5DTLrjUG8QHUztOzTTKapKj6Us/olbZR93kZB7hPBhOBmG', false, 0.66, 'admin');
insert into users (username, email, name, description, password, blocked, rate, type) values ('test', 'test@test.com', 'Test', 'User test.', '$2y$10$DG6knbMi1PBG3tmTpb1GgOKmjBxo/yQms0Q3RXR/sO4WCmKFFXSu.', false, 0.4, 'admin');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('art_lover_01', 'artlover01@email.com', 'Art Lover', 'Passionate about the beauty of classical art and sculptures. A connoisseur of timeless masterpieces, always on the lookout for the next addition to their collection.', 'aG3r$#fTq2!xZpL9', 'https://source.unsplash.com/featured/?art', false, 0.92, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('photo_artista', 'photoartista@email.com', 'Photo Artista', 'A photography enthusiast with an eye for capturing the extraordinary in the ordinary. Believes in the power of visual storytelling and seeks unique photographic prints to adorn their space.', 'bR8v%&jY1@kZsW7', 'https://source.unsplash.com/featured/?photography', false, 0.8, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('modern_canvas', 'moderncanvas@email.com', 'Modern Canvas', 'Embraces the vibrancy of modern and contemporary art. Enthusiastic about bold strokes, abstract concepts, and groundbreaking ideas. Constantly exploring the latest trends in the art world.', 'cX5t#^gU9&vM2*pK', 'https://source.unsplash.com/featured/?modernart', false, 0.84, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('print_collector', 'printcollector@email.com', 'Print Collector', 'Enjoys the diversity of art prints. From classic woodblock prints to modern digital creations, this collector appreciates the artistry and craftsmanship behind each unique print.', 'dZ6o$!iP7^uQ8*rE', 'https://source.unsplash.com/featured/?artprint', false, 0.98, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('sculpture_aficionado', 'sculptureaficionado@email.com', 'Sculpture Aficionado', 'Finds beauty in three-dimensional forms. Enthusiastic about sculptures that convey emotion, tell a story, or challenge traditional perceptions. Always seeking the next captivating piece for their collection.', 'eH1a@^bR3*yZ7!sQ', 'https://source.unsplash.com/featured/?sculpture', false, 0.87, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('minimalist_collector', 'minimalistcollector@email.com', 'Minimalist Collector', 'Finds beauty in simplicity. Appreciates minimalist art and sculptures that convey powerful messages through clean lines and subtle details. Seeks pieces that bring tranquility and sophistication to their living space.', 'fK2u!@wX4^zP9%oL', 'https://source.unsplash.com/featured/?minimalistart', false, 0.93, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('art_symphonist', 'artsymphonist@email.com', 'Art Symphonist', 'Passionate about the harmony between colors and forms.', 'aG3r$#fTq2!xZpL9', 'https://source.unsplash.com/featured/?art', false, 0.89, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('art_melody', 'artmelody@email.com', 'Art Melody', 'Seeking inspiration in the rhythmic expressions of art.', 'bR8v%&jY1@kZsW7', 'https://source.unsplash.com/featured/?classicalart', false, 0.233, 'user');
insert into users (username, email, name, description, password, img, blocked, rate, type) values ('canvas_poet', 'canvaspoet@email.com', 'Canvas Poet', 'Crafting verses inspired by strokes on the canvas.', 'cX5t#^gU9&vM2*pK', 'https://source.unsplash.com/featured/?modernart', false, 0.28, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('art_echo', 'artecho@email.com', 'Art Echo', 'Echoing the emotions captured in every stroke and hue.', 'gH6j@^iO7*rE2!sQ', 'https://source.unsplash.com/featured/?artistic', false, 0.78, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('muse_in_motion', 'museinmotion@email.com', 'Muse in Motion', 'Drawing inspiration from the dynamic flow of artistic expression.', 'hT9p!^bR3*yZ7!sQ', 'https://source.unsplash.com/featured/?motionart', false, 0.5, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('color_voyager', 'colorvoyager@email.com', 'Color Voyager', 'Embarking on a journey through the vast palette of artistic colors.', 'iO4u$!@wX8^zP2%oL', 'https://source.unsplash.com/featured/?colorfulart', false, 0.64, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('art_affinity', 'artaffinity@email.com', 'Art Affinity', 'Fostering a deep connection with diverse forms of artistic expression.', 'jP7l^&kZ6o$!iY1@', 'https://source.unsplash.com/featured/?diverseart', false, 0.577, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('serene_sketcher', 'serenesketcher@email.com', 'Serene Sketcher', 'Capturing tranquility through the gentle strokes of sketching.', 'kZ2zP9%oL#fK1u!@w', 'https://source.unsplash.com/featured/?sketching', false, 0.22, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('visual_virtuoso', 'visualvirtuoso@email.com', 'Visual Virtuoso', 'Mastering the art of visual storytelling through various mediums.', 'lX5t#^gU3&vM4*pK', 'https://source.unsplash.com/featured/?visualart', false, 0.12, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('art_zenith', 'artzenith@email.com', 'Art Zenith', 'Reaching the zenith of artistic exploration and expression.', 'mQ8v%&jY9@bR2sW7', 'https://source.unsplash.com/featured/?zenithart', false, 0.39, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('palette_pioneer', 'palettepioneer@email.com', 'Palette Pioneer', 'Pioneering new horizons in the world of color and creativity.', 'nH1a@^bR6*yZ4!sQ', 'https://source.unsplash.com/featured/?creativepalette', false, 0.47, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('art_voyager', 'artvoyager@email.com', 'Art Voyager', 'Embarking on a voyage through the vast universe of artistic expression.', 'oZ6o$!iP3^uQ9*rE', 'https://source.unsplash.com/featured/?artuniverse', false, 0.98, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('mystic_mosaic', 'mysticmosaic@email.com', 'Mystic Mosaic', 'Creating a mosaic of mystique and wonder through artistic endeavors.', 'pT7l^&kZ4o$!iY2@', 'https://source.unsplash.com/featured/?mysticart', false, 1, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('ethereal_expression', 'etherealexpression@email.com', 'Ethereal Expression', 'Transcending reality through ethereal and otherworldly art forms.', 'qU9tH1a@^zP3%fK2u!', 'https://source.unsplash.com/featured/?etherealart', false, 0.93, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('dreamscape_creator', 'dreamscapecreator@email.com', 'Dreamscape Creator', 'Crafting vivid dreams and fantasies through artistic landscapes.', 'rO4w!^xP8#zL2%uJ3', 'https://source.unsplash.com/featured/?dreamscapeart', false, 0.90, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('whimsical_wanderer', 'whimsicalwanderer@email.com', 'Whimsical Wanderer', 'Wandering through the whimsical realms of imagination and creativity.', 'sK7yZ4u!%oL#fX8^zP', 'https://source.unsplash.com/featured/?whimsicalart', false, 0.44, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artistic_adventurer', 'artisticadventurer@email.com', 'Artistic Adventurer', 'Embarking on daring artistic adventures, exploring the unknown.', 'tH2v%&jY9@kZ1o$!iP', 'https://source.unsplash.com/featured/?adventurousart', false, 0.23, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('visual_vagabond', 'visualvagabond@email.com', 'Visual Vagabond', 'Roaming freely through the vast and diverse landscapes of visual artistry.', 'uQ5l^&kZ3o$!iY6@', 'https://source.unsplash.com/featured/?vagabondart', false, 0.79, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('enigmatic_artisan', 'enigmaticartisan@email.com', 'Enigmatic Artisan', 'Crafting enigmatic and mysterious pieces that captivate the imagination.', 'vR8zL4u!%oH#fX7^jY', 'https://source.unsplash.com/featured/?enigmaticart', false, 0.91, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artful_alchemist', 'artfulalchemist@email.com', 'Artful Alchemist', 'Transforming raw creativity into a concoction of artful wonders.', 'wP9%oL#fH2v%&jY7@', 'https://source.unsplash.com/featured/?alchemistart', false, 0.39, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('colorful_catalyst', 'colorfulcatalyst@email.com', 'Colorful Catalyst', 'Igniting creativity through the vibrant sparks of colorful artistic expression.', 'xO2u!%oL#fK6*yZ4iP', 'https://source.unsplash.com/featured/?colorcatalystart', false, 0.47, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artistic_architect', 'artisticarchitect@email.com', 'Artistic Architect', 'Designing intricate worlds and structures through the lens of artistic architecture.', 'yZ6o$!iP3^uQ9*rH1a', 'https://source.unsplash.com/featured/?architectart', false, 0.56, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('mystical_maestro', 'mysticalmaestro@email.com', 'Mystical Maestro', 'Conducting the symphony of mystical artistry with a touch of magic.', 'zL3&vM4*pK1o$!iY8@', 'https://source.unsplash.com/featured/?mysticalmaestroart', false, 0.44, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artistic_echo', 'artisticecho@email.com', 'Artistic Echo', 'Creating echoes of emotion through diverse forms of artistic expression.', 'aG3r$#fTq2!xZpL9', 'https://source.unsplash.com/featured/?echoart', false, 0.97, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('whispering_canvas', 'whisperingcanvas@email.com', 'Whispering Canvas', 'Letting the canvas whisper stories that resonate with the soul.', 'bR8v%&jY1@kZsW7', 'https://source.unsplash.com/featured/?whisperart', false, 0.9, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('dream_weaver', 'dreamweaver@email.com', 'Dream Weaver', 'Weaving dreams and fantasies into the fabric of artistic creation.', 'cX5t#^gU9&vM2*pK', 'https://source.unsplash.com/featured/?dreamweaverart', false, 0.81, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artistic_visionary', 'artisticvisionary@email.com', 'Artistic Visionary', 'Visionary pursuits in the world of art, pushing the boundaries of creativity.', 'dZ6o$!iP7^uQ8*rE', 'https://source.unsplash.com/featured/?visionaryart', false, 0.84, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('color_harmonist', 'colorharmonist@email.com', 'Color Harmonist', 'Harmonizing colors in artistic endeavors to evoke emotion and beauty.', 'eH1a@^bR3*yZ7!sQ', 'https://source.unsplash.com/featured/?colorharmonyart', false, 0.13, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('imagination_alchemist', 'imagnation_alchemist@email.com', 'Imagination Alchemist', 'Transforming raw imagination into the gold of artistic brilliance.', 'fK2u!@wX4^zP9%oL', 'https://source.unsplash.com/featured/?imaginationalchemistart', false, 0.01, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('serene_strokes', 'serenestrokes@email.com', 'Serene Strokes', 'Conveying serenity through gentle strokes on the canvas of life.', 'gH6j@^iO7*rE2!sQ', 'https://source.unsplash.com/featured/?serenestrokeart', false, 0.92, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('creative_nomad', 'creativenomad@email.com', 'Creative Nomad', 'Wandering creatively through diverse landscapes of artistic expression.', 'hT9p!^bR3*yZ7!sQ', 'https://source.unsplash.com/featured/?creativenomadart', false, 0.24, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('luminous_palette', 'luminouspalette@email.com', 'Luminous Palette', 'Illuminating artistic endeavors with a vibrant and luminous palette.', 'iO4u$!@wX8^zP2%oL', 'https://source.unsplash.com/featured/?luminouspaletteart', false, 0.66, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artful_navigator', 'artfulnavigator@email.com', 'Artful Navigator', 'Navigating the vast seas of artistic inspiration with skill and finesse.', 'jP7l^&kZ6o$!iY1@', 'https://source.unsplash.com/featured/?artfulnavigatorart', false, 0.88, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('celestial_craftsman', 'celestialcraftsman@email.com', 'Celestial Craftsman', 'Crafting art that transcends earthly boundaries and reaches for the celestial.', 'kZ2zP9%oL#fK1u!@w', 'https://source.unsplash.com/featured/?celestialcraftsmanart', false, 0.77, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('ethereal_artist', 'etherealartist@email.com', 'Ethereal Artist', 'Creating art that evokes a sense of the ethereal and otherworldly.', 'lX5t#^gU3&vM4*pK', 'https://source.unsplash.com/featured/?etherealartistart', false, 0.87, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('artistic_navigator', 'artisticnavigator@email.com', 'Artistic Navigator', 'Navigating the vast sea of artistic expression with passion and curiosity.', 'mQ8v%&jY9@bR2sW7', 'https://source.unsplash.com/featured/?artisticnavigatorart', false, 0.99, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('whimsical_crafter', 'whimsicalcrafter@email.com', 'Whimsical Crafter', 'Crafting whimsical and imaginative pieces that bring joy and wonder.', 'nH1a@^bR6*yZ4!sQ', 'https://source.unsplash.com/featured/?whimsicalcrafterart', false, 1, 'user');
INSERT INTO users (username, email, name, description, password, img, blocked, rate, type) VALUES ('serendipity_sculptor', 'serendipitysculptor@email.com', 'Serendipity Sculptor', 'Sculpting pieces that capture the essence of serendipity and unexpected beauty.', 'oZ6o$!iP3^uQ9*rE', 'https://source.unsplash.com/featured/?serendipitysculptorart', false, 0, 'user');

insert into category (description) values ('Modern Art');
insert into category (description) values ('Classical Art');
insert into category (description) values ('Contemporary Art');
insert into category (description) values ('Abstract Art');
insert into category (description) values ('Impressionist Art');
insert into category (description) values ('Expressionist Art');
insert into category (description) values ('Surrealist Art');
insert into category (description) values ('Pop Art');
insert into category (description) values ('Realist Art');
insert into category (description) values ('Portraits');
insert into category (description) values ('Sculptures');
insert into category (description) values ('Ceramics');
insert into category (description) values ('Glass');
insert into category (description) values ('Photography');
insert into category (description) values ('Paintings');
insert into category (description) values ('Drawings');
insert into category (description) values ('Prints');

-- Paintings
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('One of the most famous paintings ever, by Leonardo da Vinci.', 'Mona Lisa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/270px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg', 3, true, 1000000000, '2023-11-23 10:00:00', '2023-11-25 18:00:00');
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('A beautiful painting by the famous Dutch painter Vincent van Gogh.', 'The Starry Night', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/270px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', 2, true, 800, '2023-11-24 12:00:00', '2023-11-26 18:00:00');
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('A masterpiece by Pablo Picasso.', 'Guernica', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/270px-PicassoGuernica.jpg', 3, true, 900, '2023-11-25 14:00:00', '2023-11-27 18:00:00');
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('Inspired by the French July Revolution of 1830.', 'Liberty Leading the People', 'auctions/liberty.png', 4, true, 700, '2023-11-26 16:00:00', '2023-11-28 18:00:00');
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('A painting of Jesus Christ by Leonardo da Vinci.', 'Salvator Mundi', 'auctions/salvator.png', 4, true, 600, '2023-11-27 18:00:00', '2023-11-29 18:00:00');
insert into auction (description, name, image, owner_id, active, starting_price, start_t, end_t) values ('The most famous painting from Gustav Klimt.', 'The Kiss', 'auctions/kiss.png', 4, true, 200, '2023-11-28 20:00:00', '2023-11-30 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A masterpiece by Claude Monet capturing the tranquility of water lilies.', 'Water Lilies', 'auctions/lillies.png', 7, true, 500, '2023-11-29 09:00:00', '2023-11-30 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A surrealist gem by René Magritte, challenging our perception.', 'The Son of Man', 'auctions/sonofman.png', 8, true, 700, '2023-11-30 11:30:00', '2023-12-02 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic American Gothic scene by Grant Wood.', 'American Gothic', 'auctions/americangothic.png', 9, true, 800, '2023-12-01 13:00:00', '2023-12-03 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful depiction of grief and war by Kathe Kollwitz.', 'Grieving Parents', 'auctions/grieving.png', 10, true, 750, '2023-12-02 15:30:00', '2023-12-04 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A stunning depiction of love in Gustav Klimt''s signature style.', 'Portrait of Adele Bloch-Bauer I', 'auctions/portrait.png', 11, true, 700, '2023-12-03 17:00:00', '2023-12-05 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A revolutionary piece by Frida Kahlo, reflecting her pain and strength.', 'The Two Fridas', 'auctions/fridas.png', 12, true, 300, '2023-12-04 09:00:00', '2023-12-06 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A dynamic and bold work by Jackson Pollock, a pioneer of abstract expressionism.', 'No. 5, 1948', 'auctions/no5.png', 13, true, 950, '2023-12-05 11:30:00', '2023-12-07 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A vibrant and lively composition by Wassily Kandinsky, a pioneer of abstract art.', 'Composition VIII', 'auctions/composition.png', 14, true, 800, '2023-12-06 13:00:00', '2023-12-08 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic piece by Edvard Munch, capturing the haunting nature of anxiety.', 'The Scream', 'auctions/scream.png', 15, true, 850, '2023-12-07 15:30:00', '2023-12-09 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking work by Andy Warhol, celebrating pop culture and consumerism.', 'Campbell''s Soup Cans', 'auctions/soup.png', 16, true, 1000, '2023-12-08 09:00:00', '2023-12-10 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A timeless piece by Michelangelo, a symbol of human potential and creativity.', 'David', 'auctions/david.png', 17, true, 1200, '2023-12-09 11:30:00', '2023-12-11 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking piece by Banksy, known for his satirical and thought-provoking street art.', 'Girl with a Balloon', 'auctions/balloon.png', 18, true, 900, '2023-12-10 13:00:00', '2023-12-12 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful work by Georgia O''Keeffe, capturing the beauty and sensuality of flowers.', 'Jimson Weed/White Flower No. 1', 'auctions/jimson.png', 19, true, 800, '2023-12-11 15:30:00', '2023-12-13 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A captivating work by Salvador Dalí, showcasing his surreal and dreamlike style.', 'The Persistence of Memory', 'auctions/persistence.png', 20, true, 950, '2023-12-12 17:00:00', '2023-12-14 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A pioneering work by Yayoi Kusama, known for her avant-garde and immersive installations.', 'Infinity Mirrored Room', 'auctions/infinity.png', 21, true, 1100, '2023-12-13 09:00:00', '2023-12-15 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking piece by Jean-Michel Basquiat, reflecting on race, culture, and society.', 'Untitled', 'auctions/untitled.png', 22, true, 1000, '2023-12-14 11:30:00', '2023-12-16 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An influential work by Diego Rivera, showcasing his social and political commentary.', 'Detroit Industry Murals', 'auctions/detroit.png', 23, true, 950, '2023-12-15 13:00:00', '2023-12-17 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A masterful work by Edward Hopper, capturing the solitude and mystery of urban life.', 'Nighthawks', 'auctions/nighthawks.png', 24, true, 900, '2023-12-16 15:30:00', '2023-12-18 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic sculpture by Auguste Rodin, representing the passion and intensity of love.', 'The Kiss', 'auctions/kiss2.png', 25, true, 850, '2023-12-17 17:00:00', '2023-12-19 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful political statement by Banksy, addressing social justice and equality.', 'Love is in the Bin', 'auctions/love.png', 26, true, 800, '2023-12-18 09:00:00', '2023-12-20 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A dynamic and energetic piece by Keith Haring, known for his iconic graffiti-inspired art.', 'Untitled', 'auctions/untitled2.png', 27, true, 750, '2023-12-19 11:30:00', '2023-12-21 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A mesmerizing work by Frida Kahlo, portraying her emotional and physical struggles.', 'The Broken Column', 'auctions/broken.png', 28, true, 700, '2023-12-20 13:00:00', '2023-12-22 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A striking piece by Marc Chagall, blending dreamlike elements with vibrant colors.', 'I and the Village', 'auctions/i.png', 29, true, 850, '2023-12-21 15:30:00', '2023-12-23 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking piece by Katsushika Hokusai, depicting the iconic Great Wave off Kanagawa.', 'The Great Wave off Kanagawa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/270px-The_Great_Wave_off_Kanagawa.jpg', 30, true, 900, '2023-12-22 17:00:00', '2023-12-24 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic piece by Leonardo da Vinci, known for its detailed and realistic depiction.', 'The Last Supper', 'auctions/supper.png', 31, true, 1000, '2023-12-23 09:00:00', '2023-12-25 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A serene and delicate work by Pierre-Auguste Renoir, capturing a moment of leisure.', 'Luncheon of the Boating Party', 'auctions/luncheon.png', 32, true, 950, '2023-12-24 11:30:00', '2023-12-26 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A vibrant and colorful piece by Joan Miró, showcasing his unique abstract style.', 'The Birth of the World', 'auctions/birth.png', 33, true, 800, '2023-12-25 13:00:00', '2023-12-27 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A profound work by Hieronymus Bosch, known for its surreal and fantastical imagery.', 'The Garden of Earthly Delights', 'auctions/garden.png', 34, true, 900, '2023-12-26 15:30:00', '2023-12-28 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking work by Wassily Kandinsky, a pioneer of abstract art.', 'Composition VII', 'auctions/composition7.png', 35, true, 850, '2023-12-27 17:00:00', '2023-12-29 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking work by Pablo Picasso, a pioneer of Cubism.', 'Les Demoiselles d''Avignon', 'auctions/demoiselles.png', 36, true, 950, '2023-12-28 09:00:00', '2023-12-30 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A captivating and dreamlike work by Salvador Dalí, known for its surreal elements.', 'Swans Reflecting Elephants', 'auctions/swans.png', 37, true, 900, '2023-12-29 11:30:00', '2023-12-31 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic and enigmatic piece by Johannes Vermeer, known for its use of light.', 'Girl with a Pearl Earring', 'auctions/girl.png', 38, true, 800, '2023-12-30 13:00:00', '2024-01-01 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A revolutionary work by Marcel Duchamp, challenging traditional notions of art.', 'Fountain', 'auctions/fountain.png', 39, true, 850, '2023-12-31 15:30:00', '2024-01-02 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A thought-provoking work by Grant Wood, an iconic representation of rural America.', 'Daughters of Revolution', 'auctions/daughters.png', 40, true, 800, '2024-01-01 17:00:00', '2024-01-03 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A masterful work by Rembrandt, showcasing his skill in capturing human emotions.', 'The Night Watch', 'auctions/night.png', 41, true, 1000, '2024-01-02 09:00:00', '2024-01-04 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful and emotional work by Caravaggio, known for his use of chiaroscuro.', 'The Supper at Emmaus', 'auctions/emmaus.png', 42, true, 950, '2024-01-03 11:30:00', '2024-01-05 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A breathtaking landscape by Thomas Cole, a prominent figure in the Hudson River School.', 'The Oxbow', 'auctions/oxbow.png', 43, true, 900, '2024-01-04 13:00:00', '2024-01-06 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A classic and iconic work by Jean-Auguste-Dominique Ingres, portraying a timeless beauty.', 'La Grande Odalisque', 'auctions/odalisque.png', 44, true, 850, '2024-01-05 15:30:00', '2024-01-07 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A striking and enigmatic work by Giorgio de Chirico, a precursor to the Surrealist movement.', 'The Song of Love', 'auctions/song.png', 45, true, 800, '2024-01-06 17:00:00', '2024-01-08 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A groundbreaking work by Claude Monet, capturing the beauty of water lilies.', 'Water Lilies and Japanese Bridge', 'auctions/water.png', 46, true, 900, '2024-01-07 09:00:00', '2024-01-09 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A thought-provoking work by Yves Klein, known for his use of vibrant blue pigment.', 'IKB 191', 'auctions/ikb.png', 47, true, 950, '2024-01-08 11:30:00', '2024-01-10 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A mesmerizing piece by Roy Lichtenstein, a leading figure in the Pop Art movement.', 'Drowning Girl', 'auctions/drowning.png', 48, true, 800, '2024-01-09 13:00:00', '2024-01-11 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful and emotional work by Egon Schiele, known for his expressive and raw style.', 'Death and the Maiden', 'auctions/death.png', 49, true, 850, '2024-01-10 15:30:00', '2024-01-12 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic work by Hokusai, featuring his detailed and intricate depiction of nature.', 'Red Fuji', 'auctions/red.png', 50, true, 800, '2024-01-11 17:00:00', '2024-01-13 18:00:00');

-- Photographs
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A captivating photograph capturing the essence of urban life by Daido Moriyama.', 'Tokyo Street', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Daido_Moriyama_-_Tokyo_Street_-_Google_Art_Project.jpg/270px-Daido_Moriyama_-_Tokyo_Street_-_Google_Art_Project.jpg', 2, true, 30, '2024-01-12 09:00:00', '2024-01-14 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A stunning nature photograph by Ansel Adams, showcasing the grandeur of Yosemite National Park.', 'Moonrise, Hernandez, New Mexico', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Moonrise%2C_Hernandez%2C_New_Mexico_%28Ansel_Adams%29.jpg/270px-Moonrise%2C_Hernandez%2C_New_Mexico_%28Ansel_Adams%29.jpg', 4, true, 550, '2024-01-13 11:30:00', '2024-01-15 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A thought-provoking conceptual photograph by Cindy Sherman, known for her exploration of identity.', 'Untitled Film Still #21', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Cindy_Sherman_Untitled_Film_Still_21.jpg/270px-Cindy_Sherman_Untitled_Film_Still_21.jpg', 3, true, 20, '2024-01-14 13:00:00', '2024-01-16 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A powerful documentary photograph by Dorothea Lange, capturing the struggles during the Great Depression.', 'Migrant Mother', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Lange-MigrantMother02.jpg/270px-Lange-MigrantMother02.jpg', 2, true, 50, '2024-01-15 15:30:00', '2024-01-17 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A modern and dynamic photograph by Steve McCurry, known for his iconic image of the Afghan Girl.', 'Afghan Girl', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Steve_McCurry_-_Afghan_Girl.jpg/270px-Steve_McCurry_-_Afghan_Girl.jpg', 4, true, 15, '2024-01-16 17:00:00', '2024-01-18 18:00:00');

-- Prints
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A vibrant and abstract print by Wassily Kandinsky, showcasing his innovative use of color.', 'Composition X', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Vassily_Kandinsky%2C_1939_-_Composition_10.jpg/270px-Vassily_Kandinsky%2C_1939_-_Composition_10.jpg', 2, true, 7.5, '2024-01-17 09:00:00', '2024-01-19 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A whimsical and playful print by Henri Matisse, known for his use of bold shapes and colors.', 'The Snail', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Henri_Matisse%2C_1953%2C_The_Snail%2C_Tate_Modern%2C_London.jpg/270px-Henri_Matisse%2C_1953%2C_The_Snail%2C_Tate_Modern%2C_London.jpg', 2, true, 13.4, '2024-01-18 11:30:00', '2024-01-20 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A classic woodblock print by Katsushika Hokusai, featuring the iconic Great Wave off Kanagawa.', 'The Great Wave off Kanagawa (Woodblock Print)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/270px-The_Great_Wave_off_Kanagawa.jpg', 2, true, 12.5, '2024-01-19 13:00:00', '2024-01-21 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A surreal and imaginative print by René Magritte, known for his thought-provoking visual puzzles.', 'The Son of Man', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Ren%C3%A9_Magritte_-_The_Son_of_Man.jpg/270px-Ren%C3%A9_Magritte_-_The_Son_of_Man.jpg', 2, true, 20.5, '2024-01-20 15:30:00', '2024-01-22 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A dynamic and energetic print by Roy Lichtenstein, a leading figure in the Pop Art movement.', 'Whaam!', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/Roy_Lichtenstein%2C_1963%2C_Whaam%21.jpg/270px-Roy_Lichtenstein%2C_1963%2C_Whaam%21.jpg', 2, true, 10, '2024-01-21 17:00:00', '2024-01-23 18:00:00');

-- Sculptures
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A striking and modern sculpture by Alberto Giacometti, known for his slender and elongated figures.', 'Walking Man I', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Alberto_Giacometti%2C_1960%2C_Walking_Man_I%2C_tate_london.jpg/270px-Alberto_Giacometti%2C_1960%2C_Walking_Man_I%2C_tate_london.jpg', 3, true, 95, '2024-01-22 09:00:00', '2024-01-24 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('An iconic and thought-provoking sculpture by Constantin Brâncuși, showcasing simplicity and abstraction.', 'Bird in Space', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Constantin_Brancusi%2C_1923%2C_Bird_in_Space%2C_Museum_of_Modern_Art.jpg/270px-Constantin_Brancusi%2C_1923%2C_Bird_in_Space%2C_Museum_of_Modern_Art.jpg', 3, true, 120, '2024-01-23 11:30:00', '2024-01-25 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A monumental and powerful sculpture by Michelangelo, representing the biblical hero David.', 'David', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Michelangelo%27s_David_2015.jpg/270px-Michelangelo%27s_David_2015.jpg', 3, true, 100, '2024-01-24 13:00:00', '2024-01-26 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A dynamic and energetic sculpture by Alexander Calder, a pioneer of kinetic art.', 'Mobile', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Calder_mobiles_tinguely.jpg/270px-Calder_mobiles_tinguely.jpg', 3, true, 50, '2024-01-25 15:30:00', '2024-01-27 18:00:00');
INSERT INTO auction (description, name, image, owner_id, active, starting_price, start_t, end_t) VALUES ('A whimsical and playful sculpture by Niki de Saint Phalle, known for her colorful and fantastical creations.', 'Nana', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Niki_de_Saint_Phalle_Nana.jpg/270px-Niki_de_Saint_Phalle_Nana.jpg', 3, true, 90, '2024-01-26 17:00:00', '2024-01-28 18:00:00');

insert into auction_category (auction_id, category_id) values (1, 2);
insert into auction_category (auction_id, category_id) values (2, 2);
insert into auction_category (auction_id, category_id) values (3, 2);
insert into auction_category (auction_id, category_id) values (4, 2);
insert into auction_category (auction_id, category_id) values (5, 2);
insert into auction_category (auction_id, category_id) values (6, 2);
insert into auction_category (auction_id, category_id) values (7, 2);
insert into auction_category (auction_id, category_id) values (8, 2);
insert into auction_category (auction_id, category_id) values (9, 2);
insert into auction_category (auction_id, category_id) values (10, 2);
INSERT INTO auction_category (auction_id, category_id) VALUES (1, 1);
INSERT INTO auction_category (auction_id, category_id) VALUES (2, 1);
INSERT INTO auction_category (auction_id, category_id) VALUES (3, 1);


insert into bid (amount, date, user_id, auction_id) values (1100000000, '2023-01-09 06:54:57', 2, 1);
insert into bid (amount, date, user_id, auction_id) values (800, '2023-01-02 12:34:01', 3, 2);
insert into bid (amount, date, user_id, auction_id) values (1000, '2023-05-15 20:38:56', 2, 3);
insert into bid (amount, date, user_id, auction_id) values (900, '2023-04-03 20:33:56', 2, 4);
insert into bid (amount, date, user_id, auction_id) values (850, '2023-10-11 13:07:13', 2, 5);
insert into bid (amount, date, user_id, auction_id) values (490, '2023-04-09 12:42:03', 7, 6);
insert into bid (amount, date, user_id, auction_id) values (5000, '2023-06-17 16:44:26', 15, 9);
insert into bid (amount, date, user_id, auction_id) values (1200, '2023-05-02 17:00:00', 20, 3);
insert into bid (amount, date, user_id, auction_id) values (850, '2023-06-07 11:17:22', 13, 7);
insert into bid (amount, date, user_id, auction_id) values (1000, '2023-10-04 17:02:25', 15, 10);
insert into bid (amount, date, user_id, auction_id) values (1410, '2022-10-29 17:50:50', 16, 10);
insert into bid (amount, date, user_id, auction_id) values (890, '2022-11-29 13:00:00', 42, 8);
insert into bid (amount, date, user_id, auction_id) values (1320, '2023-04-27 16:26:35', 14, 2);
insert into bid (amount, date, user_id, auction_id) values (6000, '2023-01-10 06:59:30', 12, 9);
insert into bid (amount, date, user_id, auction_id) values (1250000000, '2022-10-03 06:41:27', 13, 1);
insert into bid (amount, date, user_id, auction_id) values (2000000000, '2022-10-19 10:23:55', 18, 1);
insert into bid (amount, date, user_id, auction_id) values (1030, '2023-01-18 16:17:31', 27, 11);
insert into bid (amount, date, user_id, auction_id) values (930, '2022-12-13 01:42:01', 49, 35);
insert into bid (amount, date, user_id, auction_id) values (940, '2023-02-06 16:06:48', 24, 2);
insert into bid (amount, date, user_id, auction_id) values (3200, '2023-02-28 15:14:58', 12, 48);
insert into bid (amount, date, user_id, auction_id) values (820, '2023-01-16 13:09:45', 44, 54);
insert into bid (amount, date, user_id, auction_id) values (1500, '2023-06-10 04:24:12', 43, 41);
insert into bid (amount, date, user_id, auction_id) values (115.88, '2023-04-21 00:48:46', 50, 51);
insert into bid (amount, date, user_id, auction_id) values (5000, '2023-08-06 09:40:26', 49, 23);
insert into bid (amount, date, user_id, auction_id) values (2000, '2023-01-26 15:46:23', 10, 31);
insert into bid (amount, date, user_id, auction_id) values (1501, '2023-03-19 21:35:53', 49, 41);
insert into bid (amount, date, user_id, auction_id) values (1600, '2023-07-10 20:35:20', 43, 39);
insert into bid (amount, date, user_id, auction_id) values (3000, '2022-10-09 19:34:07', 20, 28);
insert into bid (amount, date, user_id, auction_id) values (1800, '2023-03-13 16:36:05', 43, 42);
insert into bid (amount, date, user_id, auction_id) values (1850, '2023-01-03 15:26:11', 15, 32);
insert into bid (amount, date, user_id, auction_id) values (1400, '2023-08-08 01:29:07', 27, 54);
insert into bid (amount, date, user_id, auction_id) values (1500, '2023-09-12 09:20:54', 4, 25);
insert into bid (amount, date, user_id, auction_id) values (1920, '2022-10-08 14:58:41', 29, 41);
insert into bid (amount, date, user_id, auction_id) values (1400, '2023-10-01 17:55:14', 35, 30);
insert into bid (amount, date, user_id, auction_id) values (1700, '2022-12-31 14:05:01', 14, 29);
insert into bid (amount, date, user_id, auction_id) values (2000, '2022-12-23 05:56:27', 7, 50);
insert into bid (amount, date, user_id, auction_id) values (2100, '2023-08-20 23:32:36', 10, 11);
insert into bid (amount, date, user_id, auction_id) values (1905, '2022-12-18 23:16:55', 33, 12);
insert into bid (amount, date, user_id, auction_id) values (1500, '2023-04-04 05:23:07', 9, 21);
insert into bid (amount, date, user_id, auction_id) values (3000, '2022-12-03 18:12:52', 12, 34);
insert into bid (amount, date, user_id, auction_id) values (4000, '2023-09-29 15:50:47', 33, 26);
insert into bid (amount, date, user_id, auction_id) values (10000, '2022-12-30 02:53:44', 2, 32);
insert into bid (amount, date, user_id, auction_id) values (5000, '2023-02-27 04:20:08', 26, 62);
insert into bid (amount, date, user_id, auction_id) values (6200, '2023-10-05 02:06:06', 25, 53);
insert into bid (amount, date, user_id, auction_id) values (7000, '2023-10-22 01:59:59', 22, 33);
insert into bid (amount, date, user_id, auction_id) values (20000, '2023-09-01 11:54:48', 25, 41);
insert into bid (amount, date, user_id, auction_id) values (50000, '2022-11-13 14:42:33', 23, 14);
insert into bid (amount, date, user_id, auction_id) values (10000, '2023-05-02 20:34:28', 50, 34);
insert into bid (amount, date, user_id, auction_id) values (20000, '2022-12-01 18:22:43', 50, 61);
insert into bid (amount, date, user_id, auction_id) values (30000, '2022-12-10 12:35:03', 50, 25);

/*
insert into comment (message, date, source_user_id) values ('Etiam vel augue.', '2023-10-11 20:10:37', 25);
insert into comment (message, date, source_user_id) values ('Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2023-09-26 04:15:27', 46);
insert into comment (message, date, source_user_id) values ('Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2023-09-22 12:21:33', 8);
insert into comment (message, date, source_user_id) values ('Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2023-10-10 10:25:42', 14);
insert into comment (message, date, source_user_id) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2023-10-04 19:35:41', 10);
insert into comment (message, date, source_user_id) values ('Maecenas pulvinar lobortis est.', '2023-09-22 21:21:16', 39);
insert into comment (message, date, source_user_id) values ('Vivamus vestibulum sagittis sapien.', '2023-09-16 10:53:43', 2);
insert into comment (message, date, source_user_id) values ('Morbi quis tortor id nulla ultrices aliquet.', '2023-09-20 03:51:47', 5);
insert into comment (message, date, source_user_id) values ('Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2023-10-07 03:08:13', 10);
insert into comment (message, date, source_user_id) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2023-10-13 21:34:11', 22);
insert into comment (message, date, source_user_id) values ('Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2023-10-08 20:37:44', 3);
insert into comment (message, date, source_user_id) values ('Pellentesque viverra pede ac diam.', '2023-10-20 21:04:37', 37);
insert into comment (message, date, source_user_id) values ('Duis at velit eu est congue elementum.', '2023-10-06 08:46:29', 24);
insert into comment (message, date, source_user_id) values ('Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2023-10-16 13:18:26', 26);
insert into comment (message, date, source_user_id) values ('Nam tristique tortor eu pede.', '2023-10-20 02:46:39', 12);
insert into comment (message, date, source_user_id) values ('Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2023-10-07 15:40:52', 7);
insert into comment (message, date, source_user_id) values ('Vestibulum ac est lacinia nisi venenatis tristique.', '2023-10-16 11:23:57', 18);
insert into comment (message, date, source_user_id) values ('Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2023-09-20 13:53:58', 29);
insert into comment (message, date, source_user_id) values ('Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2023-09-30 01:17:44', 47);
insert into comment (message, date, source_user_id) values ('Nunc nisl.', '2023-09-18 18:51:08', 35);
insert into comment (message, date, source_user_id) values ('Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2023-10-15 14:04:07', 33);
insert into comment (message, date, source_user_id) values ('Morbi porttitor lorem id ligula.', '2023-10-02 06:16:12', 19);
insert into comment (message, date, source_user_id) values ('Curabitur in libero ut massa volutpat convallis.', '2023-10-12 23:30:20', 34);
insert into comment (message, date, source_user_id) values ('Donec dapibus.', '2023-09-13 23:37:55', 4);
insert into comment (message, date, source_user_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2023-09-18 19:44:32', 7);
insert into comment (message, date, source_user_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2023-09-25 22:08:31', 42);
insert into comment (message, date, source_user_id) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2023-09-27 15:03:06', 16);
insert into comment (message, date, source_user_id) values ('Duis bibendum.', '2023-09-26 05:59:28', 18);
insert into comment (message, date, source_user_id) values ('In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2023-10-11 11:24:09', 39);
insert into comment (message, date, source_user_id) values ('Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2023-10-09 20:57:49', 4);
insert into comment (message, date, source_user_id) values ('Integer ac neque. Duis bibendum.', '2023-10-16 14:36:51', 43);
insert into comment (message, date, source_user_id) values ('Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2023-10-17 02:03:51', 20);
insert into comment (message, date, source_user_id) values ('Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2023-10-08 00:08:36', 21);
insert into comment (message, date, source_user_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2023-09-28 05:07:52', 36);
insert into comment (message, date, source_user_id) values ('Proin interdum mauris non ligula pellentesque ultrices.', '2023-09-29 04:31:07', 23);
insert into comment (message, date, source_user_id) values ('Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '2023-10-14 18:24:00', 2);
insert into comment (message, date, source_user_id) values ('Mauris lacinia sapien quis libero.', '2023-09-23 22:48:33', 24);
insert into comment (message, date, source_user_id) values ('Proin risus.', '2023-10-19 19:57:29', 30);
insert into comment (message, date, source_user_id) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2023-10-18 09:19:47', 24);
insert into comment (message, date, source_user_id) values ('Proin at turpis a pede posuere nonummy.', '2023-10-10 15:34:50', 25);
*/

insert into comment (message, date, source_user_id) values ('Andreia is the best admin ever!', '2023-10-11 20:10:37', 3);
insert into comment (message, date, source_user_id) values ('João is an excellent business man from Mirandela!', '2023-09-26 04:15:27', 4);
insert into comment (message, date, source_user_id) values ('This is my friend Pedro Marcelino, a very trust-worthy auctioneer!', '2023-10-11 20:10:37', 2);
insert into comment (message, date, source_user_id) values ('I have known Pedro for a long time, he is a very good auctioneer.', '2023-09-26 04:15:27', 4);
insert into comment (message, date, source_user_id) values ('Is it really the Mona Lisa for auction? Wow!', '2023-10-11 20:10:37', 3);
insert into comment (message, date, source_user_id) values ('I love this painting!', '2023-09-26 04:15:27', 4);


insert into comment_user (comment_id, user_id, rating) values (1, 1, 1);
insert into comment_user (comment_id, user_id, rating) values (2, 2, 1);
insert into comment_user (comment_id, user_id, rating) values (3, 3, 1);
insert into comment_user (comment_id, user_id, rating) values (4, 3, 1);


insert into notifications (message, date, is_seen, user_id) values ('New Comment', '2023-09-19 04:49:12', false, 3);
insert into notifications (message, date, is_seen) values ('New Bid', '2023-10-07 13:24:11', false);
insert into notifications (message, date, is_seen) values ('New Bid', '2023-09-29 07:23:20', true);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-09-14 17:49:37', false);
insert into notifications (message, date, is_seen) values ('Auction Began', '2023-09-13 14:55:23', true);
insert into notifications (message, date, is_seen) values ('New Comment', '2023-10-18 00:19:08', false);
insert into notifications (message, date, is_seen) values ('You Won', '2023-10-07 06:21:31', false);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-10-08 10:27:52', false);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-10-14 11:21:13', true);
insert into notifications (message, date, is_seen) values ('You Won', '2023-09-30 09:00:58', false);
insert into notifications (message, date, is_seen) values ('You Won', '2023-10-08 04:04:54', true);
insert into notifications (message, date, is_seen) values ('You Won', '2023-10-14 17:27:17', false);
insert into notifications (message, date, is_seen) values ('New Bid', '2023-10-10 18:12:23', false);
insert into notifications (message, date, is_seen) values ('You Lost', '2023-10-13 15:26:52', true);
insert into notifications (message, date, is_seen) values ('New Comment', '2023-09-29 05:05:35', true);
insert into notifications (message, date, is_seen) values ('Auction Began', '2023-09-15 20:47:27', false);
insert into notifications (message, date, is_seen) values ('New Comment', '2023-10-03 05:31:35', false);
insert into notifications (message, date, is_seen) values ('You Lost', '2023-09-22 22:28:04', false);
insert into notifications (message, date, is_seen) values ('New Comment', '2023-09-25 22:16:28', false);
insert into notifications (message, date, is_seen) values ('New Bid', '2023-09-19 08:28:35', false);
insert into notifications (message, date, is_seen) values ('You Won', '2023-10-22 23:35:25', false);
insert into notifications (message, date, is_seen) values ('You Lost', '2023-09-15 23:04:01', true);
insert into notifications (message, date, is_seen) values ('You Won', '2023-09-21 21:27:04', true);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-10-17 13:42:24', true);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-10-03 04:04:25', false);
insert into notifications (message, date, is_seen) values ('Auction Began', '2023-10-03 22:24:34', true);
insert into notifications (message, date, is_seen) values ('Auction Ended', '2023-10-17 12:28:06', true);
insert into notifications (message, date, is_seen) values ('Auction Began', '2023-10-17 04:23:19', true);
insert into notifications (message, date, is_seen) values ('Auction Began', '2023-10-10 03:23:02', true);
insert into notifications (message, date, is_seen) values ('New Bid', '2023-10-13 05:08:46', false);

insert into auction_save (user_id, auction_id) values (1, 1);
insert into auction_save (user_id, auction_id) values (1, 2);
insert into auction_save (user_id, auction_id) values (1, 3);
insert into auction_save (user_id, auction_id) values (2, 1);
insert into auction_save (user_id, auction_id) values (2, 2);
insert into auction_save (user_id, auction_id) values (2, 3);
insert into auction_save (user_id, auction_id) values (3, 1);
insert into auction_save (user_id, auction_id) values (4, 2);
insert into auction_save (user_id, auction_id) values (3, 3);
insert into auction_save (user_id, auction_id) values (4, 1);
insert into auction_save (user_id, auction_id) values (4, 3);

insert into faq (question, answer) values ('Is there a reserve price on items?','Yes, sellers on LeiloArte can set a minimum price for their items. This is known as a reserve price, ensuring that the item will not be sold for less than a predetermined amount.');
insert into faq (question, answer) values ('Can I retract a bid?','No, once a bid is placed on LeiloArte, it cannot be retracted. Bidding commits you to the potential purchase, so its important to consider your bid carefully before confirming.');
insert into faq (question, answer) values ('How long does an auction typically last?','The duration of each auction is determined by the owner of the item. Sellers set the auction period to a specified length, which could range from a few days to several weeks.');
insert into faq (question, answer) values ('How do I know if I´ve been outbid?','LeiloArte provides notifications to alert you if a new bid surpasses your current highest bid. This ensures that you are aware when you have been outbid and allows you to reconsider your bidding strategy.');
insert into faq (question, answer) values ('Are there any restrictions on the types of items I can auction?','Yes, LeiloArte is an exclusive auction site dedicated to the sale of art items. As such, only art-related items are permitted for auction on this platform, maintaining a specialized focus on the art market.');
